sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
/Users/guillemcobos/anaconda3/envs/myenv/bin/python: can't open file '/Users/guillemcobos/Documents/GitHub/aquagar-results-src/make-yolo-predictions.py': [Errno 1] Operation not permitted
/Users/guillemcobos/anaconda3/envs/myenv/bin/python: can't open file '/Users/guillemcobos/Documents/GitHub/aquagar-results-src/make-yolo-predictions.py': [Errno 1] Operation not permitted
/Users/guillemcobos/anaconda3/envs/myenv/bin/python: can't open file '/Users/guillemcobos/Documents/GitHub/aquagar-results-src/make-yolo-predictions.py': [Errno 1] Operation not permitted
/Users/guillemcobos/anaconda3/envs/myenv/bin/python: can't open file '/Users/guillemcobos/Documents/GitHub/aquagar-results-src/make-yolo-predictions.py': [Errno 1] Operation not permitted
/Users/guillemcobos/anaconda3/envs/myenv/bin/python: can't open file '/Users/guillemcobos/Documents/GitHub/aquagar-results-src/make-yolo-predictions.py': [Errno 1] Operation not permitted
/Users/guillemcobos/anaconda3/envs/myenv/bin/python: can't open file '/Users/guillemcobos/Documents/GitHub/aquagar-results-src/make-yolo-predictions.py': [Errno 1] Operation not permitted
/Users/guillemcobos/anaconda3/envs/myenv/bin/python: can't open file '/Users/guillemcobos/Documents/GitHub/aquagar-results-src/make-yolo-predictions.py': [Errno 1] Operation not permitted

0: 384x640 3 plateids, 219.9ms
Speed: 10.1ms preprocess, 219.9ms inference, 13.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 agars, 142.7ms
Speed: 5.6ms preprocess, 142.7ms inference, 3.6ms postprocess per image at shape (1, 3, 384, 640)
/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/joblib/externals/loky/backend/context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[Errno 2] No such file or directory: 'sysctl'
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/joblib/externals/loky/backend/context.py", line 270, in _count_physical_cores
    cpu_info = subprocess.run(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

0: 640x640 1 vproteolyticus, 247.4ms
Speed: 5.3ms preprocess, 247.4ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)

0: 608x640 (no detections), 210.8ms
Speed: 5.1ms preprocess, 210.8ms inference, 0.6ms postprocess per image at shape (1, 3, 608, 640)

0: 608x640 1 vharveyi, 208.6ms
Speed: 4.9ms preprocess, 208.6ms inference, 1.2ms postprocess per image at shape (1, 3, 608, 640)

0: 640x640 (no detections), 221.5ms
Speed: 6.2ms preprocess, 221.5ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 224.6ms
Speed: 5.5ms preprocess, 224.6ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 215.1ms
Speed: 5.5ms preprocess, 215.1ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'plateid'}
orig_img: array([[[11, 48, 38],
        [15, 50, 40],
        [20, 54, 44],
        ...,
        [28, 27, 23],
        [28, 27, 23],
        [27, 26, 22]],

       [[16, 50, 40],
        [19, 50, 41],
        [24, 53, 44],
        ...,
        [28, 27, 23],
        [28, 27, 23],
        [27, 26, 22]],

       [[20, 45, 35],
        [22, 46, 36],
        [26, 47, 38],
        ...,
        [28, 27, 23],
        [28, 27, 23],
        [27, 26, 22]],

       ...,

       [[36, 15, 17],
        [37, 16, 18],
        [38, 17, 16],
        ...,
        [52, 26, 14],
        [51, 25, 13],
        [51, 25, 13]],

       [[38, 20, 21],
        [40, 19, 21],
        [39, 18, 17],
        ...,
        [51, 25, 13],
        [51, 25, 13],
        [51, 25, 13]],

       [[42, 24, 25],
        [40, 22, 23],
        [39, 18, 17],
        ...,
        [50, 24, 12],
        [50, 24, 12],
        [50, 24, 12]]], dtype=uint8)
orig_shape: (2592, 4608)
path: '/Users/guillemcobos/Library/CloudStorage/GoogleDrive-guillem.cobos@koabiotech.com/.shortcut-targets-by-id/1UQ_YnLRmoAqhCue-qXYNP9QhYorsiAxS/KOA Biotech/08. PRODUCTS/AQUAGAR/AA-202310-002/Raw Data/2023-11-22_18:23:52/Picture_Micro_2023-11-21_18:22:32.jpg'
probs: None
save_dir: None
speed: {'preprocess': 10.14399528503418, 'inference': 219.88987922668457, 'postprocess': 13.030052185058594}]

0: 384x640 5 plateids, 187.0ms
Speed: 11.0ms preprocess, 187.0ms inference, 13.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 agars, 185.7ms
Speed: 5.7ms preprocess, 185.7ms inference, 34.0ms postprocess per image at shape (1, 3, 384, 640)
/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/joblib/externals/loky/backend/context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[Errno 2] No such file or directory: 'sysctl'
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/joblib/externals/loky/backend/context.py", line 270, in _count_physical_cores
    cpu_info = subprocess.run(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

0: 640x640 (no detections), 243.1ms
Speed: 6.3ms preprocess, 243.1ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 222.3ms
Speed: 6.0ms preprocess, 222.3ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 212.3ms
Speed: 5.4ms preprocess, 212.3ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)

0: 640x608 (no detections), 219.6ms
Speed: 4.9ms preprocess, 219.6ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 608)

0: 640x640 (no detections), 222.9ms
Speed: 6.6ms preprocess, 222.9ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 5 bcereuss, 291.9ms
Speed: 4.7ms preprocess, 291.9ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'plateid'}
orig_img: array([[[ 91, 100, 109],
        [ 93, 102, 111],
        [ 94, 104, 111],
        ...,
        [ 92,  97,  95],
        [ 93,  98,  96],
        [ 94,  99,  97]],

       [[ 92, 101, 110],
        [ 93, 103, 110],
        [ 94, 104, 111],
        ...,
        [ 92,  97,  95],
        [ 92,  97,  95],
        [ 94,  99,  97]],

       [[ 93, 103, 110],
        [ 93, 103, 110],
        [ 94, 104, 111],
        ...,
        [ 91,  96,  94],
        [ 92,  97,  95],
        [ 93,  98,  96]],

       ...,

       [[ 32,  37,  35],
        [ 33,  38,  36],
        [ 33,  38,  36],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]],

       [[ 32,  37,  35],
        [ 32,  37,  35],
        [ 33,  38,  36],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]],

       [[ 32,  37,  35],
        [ 32,  37,  35],
        [ 32,  37,  35],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]]], dtype=uint8)
orig_shape: (2592, 4608)
path: '/Users/guillemcobos/Library/CloudStorage/GoogleDrive-guillem.cobos@koabiotech.com/.shortcut-targets-by-id/1UQ_YnLRmoAqhCue-qXYNP9QhYorsiAxS/KOA Biotech/08. PRODUCTS/AQUAGAR/AA-202310-002/Raw Data/2024-01-05 10:37:12/Picture_Micro_2024-01-06 10:37:13_24h_blanc.jpg'
probs: None
save_dir: None
speed: {'preprocess': 10.964155197143555, 'inference': 187.01505661010742, 'postprocess': 13.365983963012695}]
Traceback (most recent call last):
  File "/Users/guillemcobos/Documents/GitHub/aquagar-results-src/make-yolo-predictions.py", line 60, in <module>
    results_df.to_excel(os.path.join(experiment_folder_path, 'outputs', 'results.xlsx'), index=False)
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/excel/_xlsxwriter.py", line 199, in __init__
    super().__init__(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1219, in __init__
    self._handles = get_handle(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/Users/guillemcobos/Library/CloudStorage/GoogleDrive-guillem.cobos@koabiotech.com/.shortcut-targets-by-id/1UQ_YnLRmoAqhCue-qXYNP9QhYorsiAxS/KOA Biotech/08. PRODUCTS/AQUAGAR/AA-202310-002/Raw Data/2024-01-05 10:37:12/outputs'

0: 384x640 5 plateids, 155.7ms
Speed: 6.5ms preprocess, 155.7ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 agars, 160.6ms
Speed: 5.4ms preprocess, 160.6ms inference, 3.7ms postprocess per image at shape (1, 3, 384, 640)
/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/joblib/externals/loky/backend/context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[Errno 2] No such file or directory: 'sysctl'
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/joblib/externals/loky/backend/context.py", line 270, in _count_physical_cores
    cpu_info = subprocess.run(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

0: 640x640 (no detections), 253.5ms
Speed: 6.0ms preprocess, 253.5ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 237.1ms
Speed: 6.4ms preprocess, 237.1ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 165.0ms
Speed: 7.9ms preprocess, 165.0ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)

0: 640x608 (no detections), 218.3ms
Speed: 6.9ms preprocess, 218.3ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 608)

0: 640x640 (no detections), 218.9ms
Speed: 5.2ms preprocess, 218.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 5 bcereuss, 222.9ms
Speed: 6.9ms preprocess, 222.9ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 640)
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'plateid'}
orig_img: array([[[ 91, 100, 109],
        [ 93, 102, 111],
        [ 94, 104, 111],
        ...,
        [ 92,  97,  95],
        [ 93,  98,  96],
        [ 94,  99,  97]],

       [[ 92, 101, 110],
        [ 93, 103, 110],
        [ 94, 104, 111],
        ...,
        [ 92,  97,  95],
        [ 92,  97,  95],
        [ 94,  99,  97]],

       [[ 93, 103, 110],
        [ 93, 103, 110],
        [ 94, 104, 111],
        ...,
        [ 91,  96,  94],
        [ 92,  97,  95],
        [ 93,  98,  96]],

       ...,

       [[ 32,  37,  35],
        [ 33,  38,  36],
        [ 33,  38,  36],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]],

       [[ 32,  37,  35],
        [ 32,  37,  35],
        [ 33,  38,  36],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]],

       [[ 32,  37,  35],
        [ 32,  37,  35],
        [ 32,  37,  35],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]]], dtype=uint8)
orig_shape: (2592, 4608)
path: '/Users/guillemcobos/Library/CloudStorage/GoogleDrive-guillem.cobos@koabiotech.com/.shortcut-targets-by-id/1UQ_YnLRmoAqhCue-qXYNP9QhYorsiAxS/KOA Biotech/08. PRODUCTS/AQUAGAR/AA-202310-002/Raw Data/2024-01-05 10:37:12/Picture_Micro_2024-01-06 10:37:13_24h_blanc.jpg'
probs: None
save_dir: None
speed: {'preprocess': 6.508827209472656, 'inference': 155.66420555114746, 'postprocess': 2.146005630493164}]

0: 384x640 5 plateids, 149.9ms
Speed: 5.8ms preprocess, 149.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 agars, 162.1ms
Speed: 7.4ms preprocess, 162.1ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)
/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/joblib/externals/loky/backend/context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[Errno 2] No such file or directory: 'sysctl'
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/site-packages/joblib/externals/loky/backend/context.py", line 270, in _count_physical_cores
    cpu_info = subprocess.run(
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/guillemcobos/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

0: 640x640 (no detections), 201.8ms
Speed: 4.8ms preprocess, 201.8ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 227.1ms
Speed: 5.1ms preprocess, 227.1ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 218.4ms
Speed: 5.6ms preprocess, 218.4ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)

0: 640x608 (no detections), 203.0ms
Speed: 5.1ms preprocess, 203.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 608)

0: 640x640 (no detections), 225.6ms
Speed: 6.7ms preprocess, 225.6ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 5 bcereuss, 231.2ms
Speed: 5.3ms preprocess, 231.2ms inference, 2.8ms postprocess per image at shape (1, 3, 640, 640)
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'plateid'}
orig_img: array([[[ 91, 100, 109],
        [ 93, 102, 111],
        [ 94, 104, 111],
        ...,
        [ 92,  97,  95],
        [ 93,  98,  96],
        [ 94,  99,  97]],

       [[ 92, 101, 110],
        [ 93, 103, 110],
        [ 94, 104, 111],
        ...,
        [ 92,  97,  95],
        [ 92,  97,  95],
        [ 94,  99,  97]],

       [[ 93, 103, 110],
        [ 93, 103, 110],
        [ 94, 104, 111],
        ...,
        [ 91,  96,  94],
        [ 92,  97,  95],
        [ 93,  98,  96]],

       ...,

       [[ 32,  37,  35],
        [ 33,  38,  36],
        [ 33,  38,  36],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]],

       [[ 32,  37,  35],
        [ 32,  37,  35],
        [ 33,  38,  36],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]],

       [[ 32,  37,  35],
        [ 32,  37,  35],
        [ 32,  37,  35],
        ...,
        [ 35,  37,  31],
        [ 35,  37,  31],
        [ 35,  37,  31]]], dtype=uint8)
orig_shape: (2592, 4608)
path: '/Users/guillemcobos/Library/CloudStorage/GoogleDrive-guillem.cobos@koabiotech.com/.shortcut-targets-by-id/1UQ_YnLRmoAqhCue-qXYNP9QhYorsiAxS/KOA Biotech/08. PRODUCTS/AQUAGAR/AA-202310-002/Raw Data/2024-01-05 10:37:12/Picture_Micro_2024-01-06 10:37:13_24h_blanc.jpg'
probs: None
save_dir: None
speed: {'preprocess': 5.801916122436523, 'inference': 149.88374710083008, 'postprocess': 1.64031982421875}]
